from .insert_adv import InsertAdv
from .append_irr import AppendIrr
from .back_trans import BackTrans
from .word_case import WordCase
from .contraction import Contraction
from .swap_named_ent import SwapNamedEnt
from .keyboard import Keyboard
from .mlm_suggestion import MLMSuggestion
from .swap_num import SwapNum
from .ocr import Ocr
from .punctuation import Punctuation
from .reverse_neg import ReverseNeg
from .spelling_error import SpellingError
from .tense import Tense
from .twitter_type import TwitterType
from .typos import Typos
from .swap_syn_word_embedding import SwapSynWordEmbedding
from .swap_ant_wordnet import SwapAntWordNet
from .swap_syn_wordnet import SwapSynWordNet
from .prejudice import Prejudice

