from .cn_append_irr import AppendIrr
from .cn_back_trans import BackTrans
from .cn_nasal import CnNasal
from .cn_wordEmbedding import CnSwapSynWordEmbedding
from .cn_insert_adv import InsertAdv
from .cn_mlm_suggestion import MLMSuggestion
from .cn_swap_num import CnSwapNum
from .cn_swap_named_ent import CnSwapNamedEnt
from .cn_spelling_error import CnSpellingError
from .cn_punctuation import CnPunctuation
from .cn_prejudice import CnPrejudice
from .cn_digit2char import CnDigit2Char
from .cn_homophones import CnHomophones
from .cn_get_synonym import CnSynonym
from .cn_get_antonym import CnAntonym
